credentials:
  usernames:
    aprendiz1:
      name: "aprendiz1"
      email: "aprendiz1@example.com"
      password: "boaz"
      role: "aprendiz"

    aprendiz2:
      name: "aprendiz2"
      email: "aprendiz2@example.com"
      password: "segredo2"
      role: "aprendiz"

    companheiro1:
      name: "companheiro1"
      email: "companheiro1@example.com"
      password: "comp@2025"
      role: "companheiro"

      Lucas Antonio :
      name: "Lucas Antonio"
      email: "mestre1@example.com"
      password: "admin"
      role: "mestre"

    mestre1:
      name: "mestre1"
      email: "mestre1@example.com"
      password: "senhamestre123"
      role: "mestre"

    mestre2:
      name: "mestre2"
      email: "mestre2@example.com"
      password: "senhamestre456"
      role: "mestre"

cookie:
  name: "loja_york_auth"
  key: "troque-por-uma-string-aleatoria-bem-grande"
  expiry_days: 300

preauthorized:
  emails: []
