credentials:
  usernames:
    aprendiz:
      name: "aprendiz"
      email: "aprendiz@example.com"
      password: "boaz"        # TEXTO PLANO
      role: "aprendiz"
    companheiro:
      name: "companheiro"
      email: "companheiro@example.com"
      password: "senhacompanheiro"     # TEXTO PLANO
      role: "companheiro"
    mestre:
      name: "mestre"
      email: "mestre@example.com"
      password: "senhamestre123"          # TEXTO PLANO
      role: "mestre"

cookie:
  name: "loja_york_auth"
  key: "troque-por-uma-string-aleatoria-bem-grande"
  expiry_days: 300

preauthorized:
  emails: []
