credentials:
  usernames:
    aprendiz:
      name: "aprendiz1"
      email: "aprendiz1@example.com"
      password: "boaz"
      role: "aprendiz"

    aprendiz:
      name: "aprendiz2"
      email: "aprendiz2@example.com"
      password: "segredo2"
      role: "aprendiz"

    companheiro:
      name: "companheiro1"
      email: "companheiro1@example.com"
      password: "comp@2025"
      role: "companheiro"

    mestre:
      name: "mestre"
      email: "mestre@example.com"
      password: "senhamestre123"
      role: "mestre"

      mestre:
      name: "mestre"
      email: "mestre@example.com"
      password: "senhamestre123"
      role: "mestre"

cookie:
  name: "loja_york_auth"
  key: "troque-por-uma-string-aleatoria-bem-grande"
  expiry_days: 300

preauthorized:
  emails: []
