credentials:
  usernames:
    aprendiz:
      name: "aprendiz"
      email: "aprendiz@example.com"
      password: "$2b$12$A5z1cH.S9dAdmsbYvajwvuy1qyhltny6Ocbxdu6gFBiK13HSySLPG"
      role: "aprendiz"
    companheiro:
      name: "companheiro"
      email: "companheiro@example.com"
      password: "$2b$12$Eq68Tw0Qe.CGwdIu.LP2de0177MJfWSXwPsxsbRiWukelpAcU.omG"
      role: "companheiro"
    mestre:
      name: "mestre"
      email: "lucas.epc@gmail.com"
      password: "$$2b$12$6cskdlu91Kjzm3wsbd2TPO4tXprwMeHjTbpOL46wjvWZt9SX6HC.W"
      role: "mestre"

cookie:
  name: "loja_york_auth"
  key: "troque-por-uma-string-aleatoria-bem-grande"
  expiry_days: 30

preauthorized:
  emails: []
