credentials:
  usernames:
    aprendiz:
      name: "aprendiz"
      email: "aprendiz@example.com"
      password: "boaz"
      role: "aprendiz"
    companheiro:
      name: "companheiro"
      email: "companheiro@example.com"
      password: "testecompanheiro"
      role: "companheiro"
    mestre:
      name: "mestre"
      email: "lucas.epc@gmail.com"
      password: "mestremestre"
      role: "mestre"

cookie:
  name: "loja_york_auth"
  key: "troque-por-uma-string-aleatoria-bem-grande"
  expiry_days: 30

preauthorized:
  emails: []
