credentials:
  usernames:
    aprendiz:
      name: "aprendiz"
      email: "aprendiz@example.com"
      password: "$2b$12$3qTsmpsXqM4bQgCM/CLnhuBBb3yjnGiKrtjcZxALI2HzAHy0w/F.W"
      role: "aprendiz"
    companheiro:
      name: "companheiro"
      email: "companheiro@example.com"
      password: "$2b$12$cVs2tu/iXbUTsEaWljedSebkccgzaASErUs4JQLktErYLndlY1aS6"
      role: "companheiro"
    mestre:
      name: "mestre"
      email: "lucas.epc@gmail.com"
      password: "$2b$12$eYhWF0jIdf/Xl6tcTjk98ub1XBEE8RZpuXe5dlb.gQjGVCirqSbE."
      role: "mestre"

cookie:
  name: "loja_york_auth"
  key: "troque-por-uma-string-aleatoria-bem-grande"
  expiry_days: 30

preauthorized:
  emails: []
