[theme]
primaryColor = "#9B1C1C"         # vermelho profundo (ação primária)
backgroundColor = "#F7FAFC"      # fundo claro
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"            # texto azul-acinzentado
font = "sans serif"
